//
//  dictionary.swift
//  LingoLeap
//
//  Created by Tyler Angert on 11/12/16.
//  Copyright © 2016 Tyler Angert. All rights reserved.
//

import Foundation

public struct span_eng {
    
    var dictionary: [String:String] = [
        "lavaplatos": "dishwasher",
        "el salido": "exit",
        "danza": "dance",
        "maestro": "teacher",
        "maestra": "teacher",
        "el elefante": "elephant",
        "tienda": "store",
        "el obispo": "bishop",
        "enseñar": "to teach",
        "el judaismo": "Judaism",
        "el impuesto": "tax",
        "vestíbulo": "hallway",
        "el hombro": "shoulder",
        "el gardín": "garden",
        "el banco": "bank",
        "el codo": "elbow",
        "el cerebro": "brain",
        "economía": "economics",
        "el río": "river",
        "el colegio": "college",
        "parar": "to stop",
        "la playa": "beach",
        "los pantelones": "pants",
        "la espalda": "back",
        "en ciclomotor": "by moped",
        "el oreja": "ear",
        "el buddismo": "Buddhism",
        "las aduanas": "customs",
        "el cuello": "neck",
        "geometría": "geometry",
        "el précio": "price",
        "en motocicleta": "by motorcycle",
        "la basura": "garbage",
        "historia": "history",
        "el museo": "museum",
        "aprender": "to learn",
        "el lión": "lion",
        "cerdo": "pig",
        "cerda": "pig",
        "el passaporte": "passport",
        "el nieve": "snow",
        "la renta": "the rent",
        "vender": "to sell",
        "la luz": "light",
        "escuela": "school",
        "la mofeta": "skunk",
        "la refrijedora": "refrigerator",
        "el caballo": "horse",
        "ir derecho": "go straight",
        "comprar": "to buy",
        "el sermón": "sermon",
        "la sala": "living room",
        "en tren": "by train",
        "el traje de bañar": "swimsuit",
        "la farmácia": "pharmacy",
        "el mano": "hand",
        "el bosque": "forest",
        "la fe": "faith",
        "la computadora": "computer",
        "el pecho": "chest",
        "la piscina": "pool",
        "la charca": "pond",
        "el dedo del pie": "toe",
        "el hogar": "home",
        "el ojo": "eye",
        "manta": "blanket",
        "química": "chemistry",
        "el lapiz": "pencil",
        "profesor": "professor",
        "profesora": "professor",
        "los zapatos": "shoes",
        "el mercado": "market",
        "perro": "dog",
        "perra": "dog",
        "la pila": "sink",
        "pez": "fish",
        "la lluvia": "rain",
        "el diccionário": "dictionary",
        "la cuesta": "the cost",
        "el anillo": "ring",
        "la officina": "office",
        "en automovíl": "by car",
        "el campo": "field",
        "acelerar": "to accelerate",
        "el estadio": "stadium",
        "en bus": "by bus",
        "gato": "cat",
        "gata": "cat",
        "el horno": "oven",
        "pagar": "to pay",
        "el cheque": "check",
        "el ángel": "angel",
        "el oso": "bear",
        "el cine": "movie theater",
        "el arco iris": "rainbow",
        "los correos": "post office",
        "el lago": "lake",
        "el cuarto": "room",
        "la cocina": "kitchen",
        "ropa anterior": "underwear",
        "costar": "to cost",
        "el cristianismo": "Christianity",
        "biología": "biology",
        "selva": "jungle",
        "azotea": "roof",
        "la estimación": "estimate",
        "alquiler": "to rent",
        "el Pápa": "Pope",
        "los pendientes": "earrings",
        "la iglesia": "church",
        "la cabeza": "head",
        "el tigre": "tiger",
        "gallina": "chicken",
        "gallo": "rooster",
        "la niebla": "fog",
        "escaleras": "stairs",
        "la biblia": "Bible",
        "el pie": "foot",
        "el estómigo": "stomach",
        "la escuela": "school",
        "el templo": "temple",
        "la biblioteca": "library",
        "el sombrero": "hat",
        "librería": "bookstore",
        "la boca": "mouth",
        "retardarse": "to break",
        "televisión": "television",
        "la casa": "house",
        "la cabra": "goat",
        "motor": "engine",
        "el libro": "book",
        "los calcetines": "socks",
        "la cuenta": "bill",
        "niebla": "cloud",
        "el bautismo": "baptism",
        "la fábrica": "factory",
        "música": "music",
        "negocio": "business",
        "escritorio": "desk",
        "microonda": "microwave",
        "la mesa": "table",
        "arte": "art",
        "sofá": "couch",
        "la profeta": "prophet",
        "el rádio": "radio",
        "el papel": "paper",
        "el catedral": "cathedral",
        "la vaca": "cow",
        "el examen": "exam",
        "ratón": "mouse",
        "contabilidad": "accounting",
        "el dedo": "finger",
        "la información": "information",
        "la entrada": "entrance",
        "el lapicero": "pen",
        "el apartamento": "apartment",
        "ducha": "shower",
        "la capa": "coat",
        "física": "physics",
        "la ventana": "window",
        "cantar": "to sing",
        "la ciudad": "city",
        "el granizo": "hail",
        "la cintura": "waist",
        "matemáticas": "math",
        "la ballena": "whale",
        "los direcciones": "directions",
        "bañera": "bathtub",
        "escribir": "to write",
        "estufa": "stove",
        "el vestido": "dress",
        "planta": "plant",
        "el baño": "bathroom",
        "informática": "computer science",
        "el puerto": "door",
        "la pierna": "leg",
        "la religión": "religion",
        "almacén": "grocery store",
        "armario": "closet",
        "la falda": "skirt",
        "ir": "to go",
        "el brazo": "arm",
        "geografía": "geography",
        "ave": "bird",
        "la muñeca": "wrist",
        "el café": "cafe",
        "en taxi": "by taxi",
        "estudiente": "student",
        "mapa": "map",
        "leer": "to read",
        "parque zoológico": "zoo",
        "a pie": "on foot",
        "los árboles": "trees",
        "el parque": "park",
        "cálculo": "calculus",
        "la naríz": "nose",
        "la universidad": "university",
        "pantalones vaqueros": "jeans",
        "en barco": "by boat",
        "águila": "eagle",
        "el aeropuerto": "airport",
        "pato": "duck",
        "pata": "duck",
        "el corazón": "heart",
        "estudiar": "to study",
        "el pelo": "hair",
        "dibujar": "to draw",
        "la colina": "hill", 
        "los guantes": "gloves", 
        "el Diós": "God",
        "el mono": "monkey",
        "la camisa": "shirt", 
        "la correa": "belt", 
        "la blusa": "blouse", 
        "el restaurante": "restaurant", 
        "la montaña": "mountain", 
        "el cielo": "heaven", 
        "la cara": "face", 
        "el infierno": "hell", 
        "orar": "to pray", 
        "el equipaje": "luggage",
        "oveja": "sheep", 
        "el relámpago": "lightning", 
        "flor": "flower", 
        "depositar": "to deposit", 
        "adorar": "to worship", 
        "la silla": "chair", 
        "álgebra": "algebra", 
        "la hospital": "hospital", 
        "la pared": "wall", 
        "cascada": "waterfall", 
        "llanta": "wheel", 
        "el océano": "ocean", 
        "lapanadería": "bakery", 
        "cama": "bed", 
        "el lobo": "wolf"
    ]
}